services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ROOTUSERNAME
      - MINIO_ROOT_PASSWORD=ROOTPASSWORD
      - MINIO_DEFAULT_BUCKETS=mybucket
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: server /data --console-address ":9001"

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
