milvus_settings:
  host: 'milvus-standalone:19530'
  username: ''
  password: ''

  db_settings:
    collection_name: "copyright"
    video_emb_dim: 512
    audio_emb_dim: 768
    HNSW:
      M: 32
      efConstruction: 200
      ef: 200

global_settings:
  minio:
    endpoint: 'minio:9000'
    access_key: 'ROOTUSERNAME'
    secret_key: 'ROOTPASSWORD'
    secure: off

  kafka:
    bootstrap_servers: [ 'kafka:9092' ]


algo_settings:
  segment_len: 10
  overlap_len: 0
  segment_step: 2
  audio_encoder_batch_size: 16
  video_encoder_batch_size: 16

indexer_settings:
  kafka_consumer_topic: 'index-input'
  kafka_producer_topic: 'index-result'

checker_settings:
  kafka_consumer_topic: 'processing-input'
  kafka_producer_topic: 'processing-result'





